// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/connection.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetBlockHeaders requires node to send requested block headers
type GetBlockHeaders struct {
	StartBlockIndex      uint64   `protobuf:"varint,1,opt,name=startBlockIndex,proto3" json:"startBlockIndex,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	MaxBlocks            uint64   `protobuf:"varint,3,opt,name=maxBlocks,proto3" json:"maxBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaders) Reset()         { *m = GetBlockHeaders{} }
func (m *GetBlockHeaders) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaders) ProtoMessage()    {}
func (*GetBlockHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{0}
}

func (m *GetBlockHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaders.Unmarshal(m, b)
}
func (m *GetBlockHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaders.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaders.Merge(m, src)
}
func (m *GetBlockHeaders) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaders.Size(m)
}
func (m *GetBlockHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaders proto.InternalMessageInfo

func (m *GetBlockHeaders) GetStartBlockIndex() uint64 {
	if m != nil {
		return m.StartBlockIndex
	}
	return 0
}

func (m *GetBlockHeaders) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *GetBlockHeaders) GetMaxBlocks() uint64 {
	if m != nil {
		return m.MaxBlocks
	}
	return 0
}

// BlockHeaders is response to GetBlockHeaders message. It may be empty if no blocks found
type BlockHeaders struct {
	BlockCount           uint64   `protobuf:"varint,1,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	BlockHeaders         [][]byte `protobuf:"bytes,2,rep,name=blockHeaders,proto3" json:"blockHeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaders) Reset()         { *m = BlockHeaders{} }
func (m *BlockHeaders) String() string { return proto.CompactTextString(m) }
func (*BlockHeaders) ProtoMessage()    {}
func (*BlockHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{1}
}

func (m *BlockHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaders.Unmarshal(m, b)
}
func (m *BlockHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaders.Marshal(b, m, deterministic)
}
func (m *BlockHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaders.Merge(m, src)
}
func (m *BlockHeaders) XXX_Size() int {
	return xxx_messageInfo_BlockHeaders.Size(m)
}
func (m *BlockHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaders proto.InternalMessageInfo

func (m *BlockHeaders) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func (m *BlockHeaders) GetBlockHeaders() [][]byte {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

// NewBlockHashes message it propagated to nodes if new block have appeared in network
type NewBlockHashes struct {
	BlockHashes          [][]byte `protobuf:"bytes,1,rep,name=blockHashes,proto3" json:"blockHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlockHashes) Reset()         { *m = NewBlockHashes{} }
func (m *NewBlockHashes) String() string { return proto.CompactTextString(m) }
func (*NewBlockHashes) ProtoMessage()    {}
func (*NewBlockHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{2}
}

func (m *NewBlockHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockHashes.Unmarshal(m, b)
}
func (m *NewBlockHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockHashes.Marshal(b, m, deterministic)
}
func (m *NewBlockHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockHashes.Merge(m, src)
}
func (m *NewBlockHashes) XXX_Size() int {
	return xxx_messageInfo_NewBlockHashes.Size(m)
}
func (m *NewBlockHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockHashes.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockHashes proto.InternalMessageInfo

func (m *NewBlockHashes) GetBlockHashes() [][]byte {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

// GetTransactions is request for transactions data
type GetTransactions struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=txHashes,proto3" json:"txHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactions) Reset()         { *m = GetTransactions{} }
func (m *GetTransactions) String() string { return proto.CompactTextString(m) }
func (*GetTransactions) ProtoMessage()    {}
func (*GetTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{3}
}

func (m *GetTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactions.Unmarshal(m, b)
}
func (m *GetTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactions.Marshal(b, m, deterministic)
}
func (m *GetTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactions.Merge(m, src)
}
func (m *GetTransactions) XXX_Size() int {
	return xxx_messageInfo_GetTransactions.Size(m)
}
func (m *GetTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactions proto.InternalMessageInfo

func (m *GetTransactions) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

// Transactions is message containing transaction data
type Transactions struct {
	Transactions         [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{4}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// NewBlock is notification that new block appeared in the network
type NewBlock struct {
	BlockHeader          []byte   `protobuf:"bytes,1,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	TxHashList           [][]byte `protobuf:"bytes,2,rep,name=txHashList,proto3" json:"txHashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlock) Reset()         { *m = NewBlock{} }
func (m *NewBlock) String() string { return proto.CompactTextString(m) }
func (*NewBlock) ProtoMessage()    {}
func (*NewBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{5}
}

func (m *NewBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlock.Unmarshal(m, b)
}
func (m *NewBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlock.Marshal(b, m, deterministic)
}
func (m *NewBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlock.Merge(m, src)
}
func (m *NewBlock) XXX_Size() int {
	return xxx_messageInfo_NewBlock.Size(m)
}
func (m *NewBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlock.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlock proto.InternalMessageInfo

func (m *NewBlock) GetBlockHeader() []byte {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *NewBlock) GetTxHashList() [][]byte {
	if m != nil {
		return m.TxHashList
	}
	return nil
}

// GetNodeData is request for data from state trie
type GetNodeData struct {
	NodeHashes           [][]byte `protobuf:"bytes,1,rep,name=nodeHashes,proto3" json:"nodeHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeData) Reset()         { *m = GetNodeData{} }
func (m *GetNodeData) String() string { return proto.CompactTextString(m) }
func (*GetNodeData) ProtoMessage()    {}
func (*GetNodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{6}
}

func (m *GetNodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeData.Unmarshal(m, b)
}
func (m *GetNodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeData.Marshal(b, m, deterministic)
}
func (m *GetNodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeData.Merge(m, src)
}
func (m *GetNodeData) XXX_Size() int {
	return xxx_messageInfo_GetNodeData.Size(m)
}
func (m *GetNodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeData.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeData proto.InternalMessageInfo

func (m *GetNodeData) GetNodeHashes() [][]byte {
	if m != nil {
		return m.NodeHashes
	}
	return nil
}

// NodeData is message containing node data in format: nodeHash||nodeValue
type NodeData struct {
	Nodes                [][]byte `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeData) Reset()         { *m = NodeData{} }
func (m *NodeData) String() string { return proto.CompactTextString(m) }
func (*NodeData) ProtoMessage()    {}
func (*NodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_011ecb1cf68a50b8, []int{7}
}

func (m *NodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeData.Unmarshal(m, b)
}
func (m *NodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeData.Marshal(b, m, deterministic)
}
func (m *NodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeData.Merge(m, src)
}
func (m *NodeData) XXX_Size() int {
	return xxx_messageInfo_NodeData.Size(m)
}
func (m *NodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeData.DiscardUnknown(m)
}

var xxx_messageInfo_NodeData proto.InternalMessageInfo

func (m *NodeData) GetNodes() [][]byte {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBlockHeaders)(nil), "protocol.GetBlockHeaders")
	proto.RegisterType((*BlockHeaders)(nil), "protocol.BlockHeaders")
	proto.RegisterType((*NewBlockHashes)(nil), "protocol.NewBlockHashes")
	proto.RegisterType((*GetTransactions)(nil), "protocol.GetTransactions")
	proto.RegisterType((*Transactions)(nil), "protocol.Transactions")
	proto.RegisterType((*NewBlock)(nil), "protocol.NewBlock")
	proto.RegisterType((*GetNodeData)(nil), "protocol.GetNodeData")
	proto.RegisterType((*NodeData)(nil), "protocol.NodeData")
}

func init() { proto.RegisterFile("protocol/connection.proto", fileDescriptor_011ecb1cf68a50b8) }

var fileDescriptor_011ecb1cf68a50b8 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xab, 0x12, 0xa7, 0x8b, 0x85, 0xc5, 0x43, 0x14, 0x91, 0xb0, 0xa7, 0x5c, 0xaa,
	0x50, 0xbf, 0x41, 0x15, 0xaa, 0x50, 0x7a, 0x08, 0x7e, 0x81, 0x4d, 0x32, 0x60, 0xb1, 0xee, 0x4a,
	0x76, 0xa4, 0xf9, 0xf8, 0x92, 0xc9, 0xbf, 0xdd, 0x1e, 0xdf, 0x6f, 0xde, 0xcb, 0xbc, 0x1d, 0x02,
	0x77, 0xbf, 0xb5, 0x25, 0x5b, 0xda, 0xe3, 0x73, 0x69, 0x8d, 0xc1, 0x92, 0x0e, 0xd6, 0x3c, 0x31,
	0x93, 0xf1, 0x30, 0x52, 0x27, 0x58, 0x6e, 0x91, 0x36, 0x47, 0x5b, 0x7e, 0xbf, 0xa3, 0xae, 0xb0,
	0x76, 0x32, 0x83, 0xa5, 0x23, 0x5d, 0x77, 0xf0, 0xc3, 0x54, 0xd8, 0x24, 0x51, 0x1a, 0x65, 0x17,
	0xf9, 0x39, 0x96, 0x0f, 0x70, 0x5d, 0x70, 0x52, 0xbb, 0xaf, 0x64, 0x96, 0x46, 0x99, 0xc8, 0x27,
	0xd0, 0x4e, 0x7f, 0x74, 0xc3, 0x76, 0x97, 0xcc, 0xf9, 0x0b, 0x13, 0x50, 0x39, 0x88, 0x60, 0xeb,
	0x23, 0x00, 0x47, 0x5f, 0xed, 0x9f, 0xa1, 0x7e, 0xa1, 0x47, 0xa4, 0x02, 0x51, 0x78, 0xfe, 0x64,
	0x96, 0xce, 0x33, 0x91, 0x07, 0x4c, 0xad, 0xe1, 0x66, 0x8f, 0xa7, 0xcd, 0xd0, 0x00, 0x9d, 0x4c,
	0x61, 0x51, 0x4c, 0x32, 0x89, 0x38, 0xe4, 0x23, 0xb5, 0xe2, 0x03, 0x7c, 0xd6, 0xda, 0x38, 0xcd,
	0x27, 0x72, 0xf2, 0x1e, 0x62, 0x6a, 0x82, 0xc4, 0xa8, 0xd5, 0x1a, 0x44, 0xe0, 0x55, 0x20, 0xc8,
	0xd3, 0xbd, 0x3f, 0x60, 0x6a, 0x07, 0xf1, 0x50, 0x6b, 0x2a, 0xc4, 0x95, 0xf9, 0x9d, 0x63, 0x21,
	0x46, 0xed, 0x21, 0xba, 0x6d, 0xbb, 0x83, 0xa3, 0xfe, 0x99, 0x1e, 0x51, 0x2b, 0x58, 0x6c, 0x91,
	0xf6, 0xb6, 0xc2, 0x37, 0x4d, 0xba, 0xb5, 0x1b, 0x5b, 0x61, 0x50, 0xd7, 0x23, 0x2a, 0x85, 0x78,
	0xf4, 0xde, 0xc2, 0x65, 0x3b, 0x19, 0x6c, 0x9d, 0x28, 0xae, 0xf8, 0x67, 0x78, 0xf9, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xdd, 0xd6, 0x63, 0xa2, 0x30, 0x02, 0x00, 0x00,
}
